### ISSUE TITLE
The online tour web link got 404 not found

### ISSUE THREAD

**Issue by neuyilan** [streampipes/streampipes-installer#14]
![image](https://user-images.githubusercontent.com/6237070/118248133-89a19080-b4d6-11eb-8ff0-406b98fb3406.png)

As shown above, the online tour web link[1]  in the compose document[2] is wrong.
[1]https://streampipes.apache.org/docs/docs/user-guide-tour/
[2]https://github.com/apache/incubator-streampipes-installer/tree/master/compose

**Comment by dominikriemer** [comment]
Thanks @neuyilan for reporting this!
I've fixed the broken link in the dev branch - unfortunately this will be in master only after our next ASF release.
We just recently did a documentation update and removed the online tour - hopefully the current documentation helps in doing the first steps with StreamPipes.
