### ISSUE TITLE
usage of ifconfig is deprecated

### ISSUE THREAD

**Issue by afaul** [streampipes/streampipes-installer#4]
In many linux distributions (archlinux, centos) is ifconfig marked as deprecated and therfore not installed by default. Instead there is the command ip (from the package iproute2) which replaces ifconfig.

**Comment by tenthe** [comment]
Thank you very much for your feedback. We appreciate it.
Can we directly replace it or do we have to be aware of something?
Have you already tested it within your installer?

**Comment by afaul** [comment]
You can simply replace "ifconfig" with "ip address list". The regex for the IP adresses can be the same.
I already changed the streampipes file acordingly and tested it without a problem. 

See the output of the git diff command below for the made modifications.
````diff --git a/osx_linux/streampipes b/osx_linux/streampipes
index e5c4abb..0cabd89 100755
--- a/osx_linux/streampipes
+++ b/osx_linux/streampipes
@@ -1,5 +1,5 @@
 #!/bin/bash
-if [ -z "$1" ] || [ "$#" -lt 1 ]; 
+if [ -z "$1" ] || [ "$#" -lt 1 ];
 then
 	echo "Use 'streampipes start' to start StreamPipes, 'streampipes stop' to stop it, and 'streampipes clean' to remove streampipes."
 	exit 1
@@ -27,11 +27,11 @@ then
 		curl https://raw.githubusercontent.com/streampipes/preview-docker/master/docker-compose.yml > ./tmpl-docker-compose.yml
 	fi
 
-	if command -v ifconfig;
+	if command -v ip;
 	then
 		# If Unix
 		#        ip=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | head -1)
-		rawip=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
+		rawip=$(ip address list | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
 
 		rawip=`echo $rawip | sed 's/(%s)*\n/ /g'`
 		IFS=' ' declare -a 'allips=($rawip)'
@@ -44,8 +44,8 @@ then
 		select opt in "${allips[@]}"
 		do
 		if [ -z "${opt}" ];
-			then 
-				echo "Wrong input select one of the options"; 
+			then
+				echo "Wrong input select one of the options";
 			else
 				ip="$opt"
````

**Comment by tenthe** [comment]
Thank you for your code example.
I changed it and merged it into the develop branch. It will be added into master in our next release.
I had a problem on OSX. I had to install iproute2mac with brew. Do you know is there any other workaround on OSX to run the ip command?

**Comment by afaul** [comment]
I'm not used to OSX. Therefor I don't know if there is an workaround to run the ip command on OSX.
My approach would be to test if ip or ifconfig is available and then use whatever is available.
